ktor:
  development: true
  application:
    modules:
      - dev.rafaz.ApplicationKt.module
  deployment:
    port: 8080
jwt: #https://ktor.io/docs/configuration-file.html#config-custom
  secret: "BDIcWvBDoC6XoUZmmUygIqcfiNiR5ubO"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"
database:
  url: "jdbc:mysql://localhost:3306/test"
  driver: "com.mysql.cj.jdbc.Driver"